export default {
	USER_ALREADY_EXISTS: "Email/UserName number already exists",
	CATEGORY_ALREADY_EXISTS: "Category name already exists",
	PROVIDE_VALID_USER: "Email/UserName is required",
	OTP_ALREADY_SENT: "Already OTP sent",
	CREATE_SUCCESS: "Created Successfully",
	LOGIN_SUCCESS: "Successfully Loggedin!",
	UPDATE_SUCCESS: "Updated successfully",
	DELETE_SUCCESS: "Deleted successfully",
	LOGIN_FAILED:
		"Login Failed!! Username or password is incorrect or User is inactive or User is blocked",
	OTP_SUCCESS: "OTP successfully sent!",
	OTP_SENT_FAILED: "OTP sent failed",
	EMAIL_SENT_FAILED: "Email sent failed",
	OTP_VRIFY_FAILED: "OTP verified failed",
	OTP_VRIFY_SUCCESS: "OTP verified successfully",
	RESENT_OTP_SUCCESS: "Resend OTP sent",
	REG_FAILED: "User Registration failed",
	REG_SUCCESS: "User Registered",
	PROFILE_UPDATE_SUCCESS: "Profile Updated successfully",
	PROFILE_UPDATE_FAILED: "Profile Updated failed",
	LABEL_SUCCESS: "Success",
	LOGOUT_SUCCESS: "Logout successfully",
	LOGOUT_FAILED: "Logout failed",
	LABEL_FAILED: "Failed",
	WRONG_PSW: "Incorrect password",
	AUTH_ERR: "Authentication Error",
	EMAIL_INVALID: "Invalid Email",
	PASS_RESET_SUCCESS: "Password Reset Successfully",
	PASS_RESET_FAILED: "Password Reset Failed",
	EMAIL_OTP_INVALID: "Invalid Email/OTP",
	SOMETHING_WRONG: "Request Failed/Something Went Wrong",
	NO_DATA: "No Data Found",
	PRODUCT_EXISTS_CATEGORY: "Product already exists in this category",
	TEMPLATE_ALREADY_EXISTS: "Template already exists for the type",
	BANNER_ALREADY_EXISTS: "Banner name already exists",
	CHANNEL_ALREADY_EXISTS: "Channel already exists",
	COMPANY_ALREADY_EXISTS: "Company Email/Company UEN number already exists"
};
